### ISSUE TITLE
The Humpback Whale Sentinel Programme (HWSP)

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-issues#2]
## Network

- Title: The Humpback Whale Sentinel Programme (HWSP)
- URL: https://geonode.goosocean.org/layers/geonode_data:geonode:hwsp

## Problems found

Polygon not showing in map (spatial info visible in GeoNode)?

**Comment by SeritavdW** [comment]
> ## Network
> * Title: The Humpback Whale Sentinel Programme (HWSP)
> * URL: https://geonode.goosocean.org/layers/geonode_data:geonode:hwsp
> 
> ## Problems found
> Polygon not showing in map (spatial info visible in GeoNode)?

Same issue for SCAR: https://geonode.goosocean.org/layers/geonode_data:geonode:SCAR

**Comment by pieterprovoost** [comment]
@SeritavdW This is not fixed yet, right?

**Comment by SeritavdW** [comment]
No, but I found what the causes the issue, no polygon border. I will fix that.

**Comment by pieterprovoost** [comment]
Ok, keep me posted please! I'll keep this open until it's verifiably fixed, just in case.

**Comment by SeritavdW** [comment]
Hi Pieter. I was not able to find why the polygon outline does not show in the map. I tried uploading polygons for others as an example and the same thing happens. Most likely a format issue because EEZ shapefiles from marine regions works fine, only those I save with QGIS that cause this. Is it possible to tell what the issue is?

**Comment by SeritavdW** [comment]
Fixed.
