### ISSUE TITLE
Spatial data not showing in map

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-issues#3]
- Title: eDNA_expeditions_mwhs
- URL: https://geonode.goosocean.org/layers/geonode_data:geonode:eDNA_expeditions_mwhs

- Title: CBMP Arctic Marine Areas 
- URL: https://geonode.goosocean.org/layers/geonode_data:geonode:CBMP_Arctic_Marine_Areas_4326
(some polygons missing, some show)

- Title: The Humpback Whale Sentinel Programme (HWSP)
- URL: https://geonode.goosocean.org/layers/geonode_data:geonode:hwsp

I have an idea that this happens when a polygon crosses the global map border on the sides or top/bottom, but none of the eDNA Exp. sites cross a border so I'm not sure. All spatial data is is however visible in GeoNode for each of these layers.

**Comment by SeritavdW** [comment]
Issues fixed.

**Comment by pieterprovoost** [comment]
Thanks @SeritavdW, how did this get resolved?

**Comment by SeritavdW** [comment]
eDNA Expeditions just needed a moment
Both CBMP and HWSP have polygons who's margins overlap the map boundary in the portal. In these cases the map shows in GeoNode but not in the portal. The solution was to make the margins of the overlapping areas slightly narrower so it fits on the map. Only downside is that it creates a tiny gap on the left/right margins on the map if you zoom out further than 1 full map size, but I don't think this affects the interpretation of the area covered
